root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"

[build]
  args_bin = []
  cmd = "make build-debug"
  bin = "./bin/api-debug"
  full_bin = "dlv exec ./bin/api-debug --listen=:2345 --headless=true --api-version=2 --accept-multiclient --continue --log -- "
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "templates", "tests"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false
  delay = 1
  kill_delay = "0s"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = true
  keep_scroll = true
