# This file is used for development purposes only
# The production environment should be deployed using Orchestration tools
version: '3.8'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: dockerfile.dev.yaml
    env_file:
      - .env
    ports:
      - 5007:5007
      - 2345:2345 # Delve debugger
    environment:
      - PORT=5007
      - DB_HOST=db
    volumes:
      - .:/app
    restart: on-failure
    depends_on:
      - db

volumes:
  db_data:
    driver: local