FROM golang:1.22.5 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN make build

FROM alpine:latest as production

WORKDIR /app

COPY --from=builder /app/ /app/bin/

RUN groupadd -g 10001 appuser && \
    useradd -u 10001 -g appuser -s /bin/sh -m appuser

RUN chown -R appuser:appuser /app

USER appuser

CMD ["make", "start"]